version: "3"
services:
  # db:
  #   image : postgres
  #   restart: always
  #   environment:
  #     POSTGRES_DB: db
  #     POSTGRES_PASSWORD: db
  #     POSTGRES_USER: db

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
      POSTGRES_DB: db
    volumes:
      - ./createDB.sql:/docker-entrypoint-initdb.d/createDB.sql

  app:
    build: .
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    image: my-app
    ports:
      - "8000:8000"


    

      